import {
  CelebrationTemplate,
  PosterFormat,
} from "@/types/celebration-studio";

export const POSTER_FORMATS: PosterFormat[] = [
  {
    id: "portrait",
    label: "Social Portrait",
    sublabel: "1080 × 1350",
    width: 1080,
    height: 1350,
    aspectRatio: "4 / 5",
    recommendedFor: "Instagram & Facebook Post (Recommended)",
  },
  {
    id: "square",
    label: "Square Post",
    sublabel: "1080 × 1080",
    width: 1080,
    height: 1080,
    aspectRatio: "1 / 1",
    recommendedFor: "WhatsApp Profile & Square Feeds",
  },
  {
    id: "story",
    label: "Status / Story",
    sublabel: "1080 × 1920",
    width: 1080,
    height: 1920,
    aspectRatio: "9 / 16",
    recommendedFor: "WhatsApp Status & Instagram Stories",
  },
  {
    id: "print",
    label: "Printable Portrait",
    sublabel: "1200 × 1600",
    width: 1200,
    height: 1600,
    aspectRatio: "3 / 4",
    recommendedFor: "A4 / Poster Wall Display",
  },
];

export const CELEBRATION_TEMPLATES: CelebrationTemplate[] = [
  {
    id: "personal-celebration",
    name: "Personal Celebration",
    category: "personal",
    description: "Elegant portrait layout featuring your photograph, name, title and centenary felicitations.",
    themeColor: "#321357",
    accentColor: "#d4a72c",
    backgroundColor: "#2a0f49",
    backgroundStyle: "ceremonial-purple",
    photoConfig: {
      shape: "arch",
      borderWidth: 6,
      borderColor: "#d4a72c",
      hasGoldFrame: true,
      defaultPosition: { x: 540, y: 520, width: 440, height: 480 },
    },
    defaultTitle: "Proud Son of Takete-Ide",
    defaultMessage: "Celebrating 100 years of heritage, unity and progress.",
    defaultSalutation: "Happy Centenary Celebration!",
    defaultLocalExpression: "Agbagba Ide Agbe Wa O",
    supportedFormats: ["portrait", "square", "story", "print"],
    requiredFields: ["name", "message"],
    optionalFields: ["title", "greeting", "localExpression"],
    badgeText: "Centenary Celebrant",
  },
  {
    id: "family-felicitation",
    name: "Family Felicitation",
    category: "family",
    description: "A warm, dignified design crafted for couples and families rejoicing together on this 100-year milestone.",
    themeColor: "#245c3a",
    accentColor: "#e8c766",
    backgroundColor: "#163d26",
    backgroundStyle: "heritage-green",
    photoConfig: {
      shape: "rounded-rect",
      borderWidth: 6,
      borderColor: "#e8c766",
      hasGoldFrame: true,
      defaultPosition: { x: 540, y: 490, width: 500, height: 440 },
    },
    defaultTitle: "",
    defaultMessage: "Our family warmly congratulates the Royal Father, elders and good people of Takete-Ide on this historic centenary anniversary.",
    defaultSalutation: "Hearty Congratulations!",
    defaultSignOff: "With love & pride from the family",
    defaultLocalExpression: "A Century of Heritage · A Future of Greater Glory",
    supportedFormats: ["portrait", "square", "story", "print"],
    requiredFields: ["familyName", "message"],
    optionalFields: ["name", "greeting", "signOff", "localExpression"],
    badgeText: "Family Tribute",
  },
  {
    id: "leadership-celebration",
    name: "Leadership & Civic Celebration",
    category: "leadership",
    description: "Commanding ceremonial layout with prominent centenary crest and gold insignia for community contributors and leaders.",
    themeColor: "#321357",
    accentColor: "#d4a72c",
    backgroundColor: "#170a29",
    backgroundStyle: "royal-gold",
    photoConfig: {
      shape: "circle",
      borderWidth: 8,
      borderColor: "#d4a72c",
      hasGoldFrame: true,
      defaultPosition: { x: 540, y: 510, width: 440, height: 440 },
    },
    defaultTitle: "Community Leader & Contributor",
    defaultMessage: "Honouring our heritage and celebrating a century of community, unity and purposeful progress.",
    defaultSalutation: "Warm Felicitations!",
    defaultLocalExpression: "Faith, Unity and Progress",
    supportedFormats: ["portrait", "square", "story", "print"],
    requiredFields: ["name", "title", "message"],
    optionalFields: ["greeting", "signOff", "localExpression"],
    badgeText: "Centenary Leadership",
  },
  {
    id: "heritage-nature",
    name: "Heritage & Natural Wonders",
    category: "heritage",
    description: "Showcases authentic Takete-Ide scenery such as Obasoro Hill or Okuta Gbooro behind your portrait.",
    themeColor: "#245c3a",
    accentColor: "#d4a72c",
    backgroundColor: "#163d26",
    backgroundStyle: "photo-backdrop",
    defaultBackgroundPhoto: "obasoro-hill",
    photoConfig: {
      shape: "arch",
      borderWidth: 6,
      borderColor: "#d4a72c",
      hasGoldFrame: true,
      defaultPosition: { x: 540, y: 520, width: 420, height: 460 },
    },
    defaultTitle: "Heritage Ambassador",
    defaultMessage: "From the hilltops of Ilu-Oke to the valley of peace, celebrating 100 years of glorious roots.",
    defaultSalutation: "Honouring Our Roots",
    defaultLocalExpression: "Agbagba Ide Agbe Wa O",
    supportedFormats: ["portrait", "square", "story", "print"],
    requiredFields: ["name", "message"],
    optionalFields: ["title", "greeting", "localExpression"],
    badgeText: "Heritage Edition",
  },
  {
    id: "custom-celebration",
    name: "Create Your Own Style",
    category: "custom",
    description: "Customise approved themes, heritage backgrounds, frame styles, and custom messages to create your personal tribute.",
    themeColor: "#321357",
    accentColor: "#d4a72c",
    backgroundColor: "#2a0f49",
    backgroundStyle: "ceremonial-purple",
    photoConfig: {
      shape: "rounded-rect",
      borderWidth: 6,
      borderColor: "#d4a72c",
      hasGoldFrame: true,
      defaultPosition: { x: 540, y: 510, width: 440, height: 460 },
    },
    defaultTitle: "",
    defaultMessage: "Celebrating 100 years of heritage, unity and progress. Long live Takete-Ide!",
    defaultSalutation: "Happy Centenary Celebration!",
    defaultLocalExpression: "Omo Takete-Ide Ni Mi",
    supportedFormats: ["portrait", "square", "story", "print"],
    requiredFields: ["name", "message"],
    optionalFields: ["familyName", "title", "greeting", "signOff", "localExpression"],
    badgeText: "Custom Tribute",
  },
];
