import {
  CelebrationTemplate,
  PosterFormat,
} from "@/types/celebration-studio";

export const POSTER_FORMATS: PosterFormat[] = [
  {
    id: "portrait",
    label: "Social Portrait",
    sublabel: "1080 × 1350",
    width: 1080,
    height: 1350,
    aspectRatio: "4 / 5",
    recommendedFor: "Instagram & Facebook Post (Recommended)",
  },
  {
    id: "square",
    label: "Square Post",
    sublabel: "1080 × 1080",
    width: 1080,
    height: 1080,
    aspectRatio: "1 / 1",
    recommendedFor: "WhatsApp Profile & Square Feeds",
  },
  {
    id: "story",
    label: "Status / Story",
    sublabel: "1080 × 1920",
    width: 1080,
    height: 1920,
    aspectRatio: "9 / 16",
    recommendedFor: "WhatsApp Status & Instagram Stories",
  },
  {
    id: "print",
    label: "Printable Portrait",
    sublabel: "1200 × 1600",
    width: 1200,
    height: 1600,
    aspectRatio: "3 / 4",
    recommendedFor: "A4 / Poster Wall Display",
  },
];

export const CELEBRATION_TEMPLATES: CelebrationTemplate[] = [
  {
    id: "personal-celebration",
    name: "Personal Celebration",
    category: "personal",
    description: "Grand ceremonial portrait layout featuring an enlarged arch frame, prominent 100-year centenary crest, nameplate and congratulatory message.",
    themeColor: "#321357",
    accentColor: "#d4a72c",
    backgroundColor: "#2a0f49",
    backgroundStyle: "ceremonial-purple",
    photoConfig: {
      shape: "arch",
      borderWidth: 8,
      borderColor: "#d4a72c",
      hasGoldFrame: true,
      defaultPosition: { x: 540, y: 560, width: 560, height: 620 },
    },
    defaultTitle: "", // Must be empty by default
    defaultMessage: "Celebrating 100 years of heritage, unity and progress. Long live Takete-Ide!",
    defaultSalutation: "Happy Centenary Celebration!",
    defaultLocalExpression: "Agbagba Ide Agbe Wa O",
    supportedFormats: ["portrait", "square", "story", "print"],
    requiredFields: ["name", "message"],
    optionalFields: ["title", "greeting", "localExpression"],
    badgeText: "Centenary Celebrant",
  },
  {
    id: "family-felicitation",
    name: "Family Felicitation",
    category: "family",
    description: "A rich emerald green and gold tribute design with an extra-wide rectangular photo area for couples and families.",
    themeColor: "#245c3a",
    accentColor: "#e8c766",
    backgroundColor: "#163d26",
    backgroundStyle: "heritage-green",
    photoConfig: {
      shape: "rounded-rect",
      borderWidth: 8,
      borderColor: "#e8c766",
      hasGoldFrame: true,
      defaultPosition: { x: 540, y: 550, width: 660, height: 520 },
    },
    defaultTitle: "", // Must be empty by default
    defaultMessage: "Our family warmly congratulates the Royal Father, elders and good people of Takete-Ide on this historic centenary milestone.",
    defaultSalutation: "Hearty Congratulations!",
    defaultSignOff: "With love & pride from the family",
    defaultLocalExpression: "A Century of Heritage · A Future of Greater Glory",
    supportedFormats: ["portrait", "square", "story", "print"],
    requiredFields: ["familyName", "message"],
    optionalFields: ["name", "greeting", "signOff", "localExpression"],
    badgeText: "Family Tribute",
  },
  {
    id: "leadership-celebration",
    name: "Leadership & Civic Celebration",
    category: "leadership",
    description: "Majestic regal purple & gold composition with prominent centenary insignia, dedicated role badge, and commanding nameplate.",
    themeColor: "#321357",
    accentColor: "#d4a72c",
    backgroundColor: "#170a29",
    backgroundStyle: "royal-gold",
    photoConfig: {
      shape: "circle",
      borderWidth: 10,
      borderColor: "#d4a72c",
      hasGoldFrame: true,
      defaultPosition: { x: 540, y: 540, width: 560, height: 560 },
    },
    defaultTitle: "", // Must be empty by default
    defaultMessage: "Honouring our heritage and celebrating a century of community, unity and purposeful progress.",
    defaultSalutation: "Warm Felicitations!",
    defaultLocalExpression: "Faith, Unity and Progress",
    supportedFormats: ["portrait", "square", "story", "print"],
    requiredFields: ["name", "message"],
    optionalFields: ["title", "greeting", "signOff", "localExpression"],
    badgeText: "Centenary Leadership",
  },
  {
    id: "heritage-nature",
    name: "Heritage & Natural Wonders",
    category: "heritage",
    description: "Features authentic Takete-Ide landscape scenery (Obasoro Hill, Okuta Gbooro, Eba River) with an enlarged foreground portrait and heritage plaque.",
    themeColor: "#245c3a",
    accentColor: "#d4a72c",
    backgroundColor: "#163d26",
    backgroundStyle: "photo-backdrop",
    defaultBackgroundPhoto: "obasoro-hill",
    photoConfig: {
      shape: "arch",
      borderWidth: 8,
      borderColor: "#d4a72c",
      hasGoldFrame: true,
      defaultPosition: { x: 540, y: 560, width: 540, height: 580 },
    },
    defaultTitle: "", // Must be empty by default
    defaultMessage: "From the hilltops of Ilu-Oke to the valley of peace, celebrating 100 years of glorious roots.",
    defaultSalutation: "Honouring Our Roots",
    defaultLocalExpression: "Agbagba Ide Agbe Wa O",
    supportedFormats: ["portrait", "square", "story", "print"],
    requiredFields: ["name", "message"],
    optionalFields: ["title", "greeting", "localExpression"],
    badgeText: "Heritage Edition",
  },
  {
    id: "custom-celebration",
    name: "Create Your Own Style",
    category: "custom",
    description: "Customise approved ceremonial themes, authentic heritage backgrounds, frame styles, and custom expressions across the full poster.",
    themeColor: "#321357",
    accentColor: "#d4a72c",
    backgroundColor: "#2a0f49",
    backgroundStyle: "ceremonial-purple",
    photoConfig: {
      shape: "rounded-rect",
      borderWidth: 8,
      borderColor: "#d4a72c",
      hasGoldFrame: true,
      defaultPosition: { x: 540, y: 550, width: 580, height: 580 },
    },
    defaultTitle: "", // Must be empty by default
    defaultMessage: "Celebrating 100 years of heritage, unity and progress. Long live Takete-Ide!",
    defaultSalutation: "Happy Centenary Celebration!",
    defaultLocalExpression: "Omo Takete-Ide Ni Mi",
    supportedFormats: ["portrait", "square", "story", "print"],
    requiredFields: ["name", "message"],
    optionalFields: ["familyName", "title", "greeting", "signOff", "localExpression"],
    badgeText: "Custom Tribute",
  },
];
